firstTeam = "First"
secondTeam = "Second"
campaign = "Test"
allUnitTypes = {"infantry":"infantry", "engineers":"engineers", "mechanized":"mechanized", "light-cavalry":"light-cavalry", "med-cavalry":"med-cavalry", "heavy-cavalry":"heavy-cavalry", "light-artillery":"light-artillery", "med-artillery":"med-artillery", "heavy-artillery":"heavy-artillery", "special":"special", "corvette":"corvette", "amphibious":"amphibious", "patrol":"patrol", "cruiser":"cruiser", "destroyer":"destroyer", "battleship":"battleship", "carrier":"carrier", "attack-submarine":"attack-submarine", "missile-submarine":"missile-submarine", "light-fighter":"light-fighter", "heavy-fighter":"heavy-fighter", "bomber":"bomber", "stealth-bomber":"stealth-bomber", "recon":"recon", "transport":"transport", "drone":"drone"}
airTheater = True
unitTable = {"1st-infantry":"infantry", "1st-engineers":"engineers", "1st-mechanized":"mechanized", "1st-light-cavalry":"light-cavalry", "1st-med-cavalry":"med-cavalry", "1st-heavy-cavalry":"heavy-cavalry", "1st-light-artillery":"light-artillery", "1st-med-artillery":"med-artillery", "1st-heavy-artillery":"heavy-artillery", "1st-special":"special", "1st-corvette":"corvette", "1st-amphibious":"amphibious", "1st-patrol":"patrol", "1st-cruiser":"cruiser", "1st-destroyer":"destroyer", "1st-battleship":"battleship", "1st-carrier":"carrier", "1st-attack-submarine":"attack-submarine", "1st-missile-submarine":"missile-submarine", "1st-light-fighter":"light-fighter", "1st-heavy-fighter":"heavy-fighter", "1st-bomber":"bomber", "1st-stealth-bomber":"stealth-bomber", "1st-recon":"recon", "1st-transport":"transport", "1st-drone":"drone", "2nd-infantry":"infantry", "2nd-engineers":"engineers", "2nd-mechanized":"mechanized", "2nd-light-cavalry":"light-cavalry", "2nd-med-cavalry":"med-cavalry", "2nd-heavy-cavalry":"heavy-cavalry", "2nd-light-artillery":"light-artillery", "2nd-med-artillery":"med-artillery", "2nd-heavy-artillery":"heavy-artillery", "2nd-special":"special", "2nd-corvette":"corvette", "2nd-amphibious":"amphibious", "2nd-patrol":"patrol", "2nd-cruiser":"cruiser", "2nd-destroyer":"destroyer", "2nd-battleship":"battleship", "2nd-carrier":"carrier", "2nd-attack-submarine":"attack-submarine", "2nd-missile-submarine":"missile-submarine", "2nd-light-fighter":"light-fighter", "2nd-heavy-fighter":"heavy-fighter", "2nd-bomber":"bomber", "2nd-stealth-bomber":"stealth-bomber", "2nd-recon":"recon", "2nd-transport":"transport", "2nd-drone":"drone"}
firstTeamTable = {"1st-infantry":4, "1st-engineers":4, "1st-mechanized":6, "1st-light-cavalry":12, "1st-med-cavalry":14, "1st-heavy-cavalry":16, "1st-light-artillery":8, "1st-med-artillery":9, "1st-heavy-artillery":10, "1st-special":20, "1st-corvette":4, "1st-amphibious":4, "1st-patrol":2, "1st-cruiser":10, "1st-destroyer":8, "1st-battleship":12, "1st-carrier":16, "1st-attack-submarine":1, "1st-missile-submarine":1, "1st-light-fighter":4, "1st-heavy-fighter":8, "1st-bomber":12, "1st-stealth-bomber":10, "1st-recon":4, "1st-transport":12, "1st-drone":4}
secondTeamTable = {"2nd-infantry":4, "2nd-engineers":4, "2nd-mechanized":6, "2nd-light-cavalry":12, "2nd-med-cavalry":14, "2nd-heavy-cavalry":16, "2nd-light-artillery":8, "2nd-med-artillery":9, "2nd-heavy-artillery":10, "2nd-special":20, "2nd-corvette":4, "2nd-amphibious":4, "2nd-patrol":2, "2nd-cruiser":10, "2nd-destroyer":8, "2nd-battleship":12, "2nd-carrier":16, "2nd-attack-submarine":1, "2nd-missile-submarine":1, "2nd-light-fighter":4, "2nd-heavy-fighter":8, "2nd-bomber":12, "2nd-stealth-bomber":10, "2nd-recon":4, "2nd-transport":12, "2nd-drone":4}
firstHealthTotal = 215
secondHealthTotal = 215
fogOfWar = 1
warheads = 1
locationTable = {}

def loadGame():
    pass