firstTeam = "Rebel"
secondTeam = "British"
landTheater = True
navalTheater = False
airTheater = False
validCommands = ["move", "fire", "build", "hide", "spy", "info", "kill", "health", "freeze", "reveal", "man"]
allUnitTypes = ["infantry", "sapper", "fusilier", "grenadier", "bombadier", "hussar", "dragoon", "spy", "guard", "special", "command"] # Never used, only kept here for redundancy's sake
unitTable = {"va1":"infantry", "va2":"infantry", "va3":"infantry", "va5":"infantry", "va6":"infantry", "va7":"infantry", "va9":"infantry", "va12":"infantry", "pa1":"infantry", "pa4":"infantry", "pa6":"infantry", "pa7":"infantry", "pa8":"infantry", "nc1":"infantry", "nc3":"infantry", "md1":"infantry", "md2":"infantry", "nj2":"infantry", "nj4":"infantry", "sap1":"sapper", "sap2":"sapper", "pa1f":"fusilier", "pa2f":"fusilier", "pa3f":"fusilier", "pa4f":"fusilier", "nj1f":"fusilier", "nj2f":"fusilier", "nj3f":"fusilier", "mx1":"hussar", "mx2":"hussar", "pl":"dragoon", "mc":"dragoon", "6":"fusilier", "knphyn":"spy", "rebel-guards1":"guard", "rebel-guards2":"guard", "rebel-guards3":"guard", "crnwl":"command", "4":"infantry", "5":"infantry", "10":"infantry", "15":"infantry", "17":"infantry", "23":"infantry", "28":"infantry", "33":"infantry", "38":"infantry", "40":"infantry", "44":"infantry", "64":"infantry", "71":"infantry", "72":"infantry", "73":"infantry", "gd1":"sapper", "gd2":"sapper", "lrg":"sapper", "eb":"fusilier", "lg":"fusilier", "dp":"fusilier", "wb":"fusilier", "mg":"fusilier", "ls":"fusilier", "st":"fusilier", "mb":"fusilier", "lt1":"hussar", "lt2":"hussar", "lt3":"hussar", "gr1":"hussar", "gr2":"hussar", "gr3":"hussar", "16":"dragoon", "17":"dragoon", "jag":"dragoon", "6-1":"grenadier", "6-2":"grenadier", "12-1":"bombadier", "12-2":"bombadier", "howe":"spy", "british-guards1":"guard", "british-guards2":"guard", "greene":"command"}
firstTeamTable = {"va1":4, "va2":4, "va3":4, "va5":4, "va6":4, "va7":4, "va9":4, "va12":4, "pa1":4, "pa4":4, "pa6":4, "pa7":4, "pa8":4, "nc1":4, "nc3":4, "md1":4, "md2":4, "nj2":4, "nj4":4, "sap1":4, "sap2":4, "pa1f":6, "pa2f":6, "pa3f":6, "pa4f":6, "nj1f":6, "nj2f":6, "nj3f":6, "mx1":12, "mx2":12, "pl":16, "mc":16, "6":6, "knphyn":10, "rebel-guards1":20, "rebel-guards2":20, "rebel-guards3":20, "crnwl":20}
secondTeamTable = {"4":4, "5":4, "10":4, "15":4, "17":4, "23":4, "28":4, "33":4, "38":4, "40":4, "44":4, "64":4, "71":4, "72":4, "73":4, "gd1":4, "gd2":4, "lrg":4, "eb":6, "lg":6, "dp":6, "wb":6, "mg":6, "ls":6, "st":6, "mb":6, "lt1":12, "lt2":12, "lt3":12, "gr1":12, "gr2":12, "gr3":12, "16":16, "17":16, "jag":16, "6-1":8, "6-2":8, "12-1":10, "12-2":10, "howe":10, "british-guards1":20, "british-guards2":20, "greene":20}
firstHealthTotal = 278
secondHealthTotal = 342
firstHealth = sum(firstTeamTable.values())
secondHealth = sum(secondTeamTable.values())
healthTable = {"infantry":4, "sapper":4, "fusilier":6, "grenadier":8, "bombadier":10, "spy":10, "hussar":12, "dragoon":16, "special":20, "command":20, "guard":20}
movementTable = {"bombadier":5, "dragoon":5, "spy":5, "command":5, "infantry":10, "sapper":10, "grenadier":10, "hussar":10, "special":10, "fusilier":15, "guard":5}
attackTable = {"infantry":4, "sapper":4, "fusilier":4, "grenadier":4, "bombadier":4, "spy":4, "hussar":12, "dragoon":20, "special":20, "command":20, "guard":20}
fireTable = {"grenadier":8, "bombadier":10, "hussar":12, "dragoon":20}
buildTable = {"infantry":4, "sapper":8}
depthchargeTable = {}
sortieTable = {}
sortieDefenseTable = {}
torpedoTable = {}
spyTable = {"infantry":6, "sapper":6, "fusilier":6}
hideTable = {"infantry":1, "sapper":1, "fusilier":1, "grenadier":1, "spy":1, "special":1}
moveAndFire = ["infantry", "sapper", "fusilier", "hussar", "dragoon", "special"]
headingTable = {}