firstTeam = "Rebel"
secondTeam = "British"
campaign = "Brandywine"
allUnitTypes = {"infantry":"infantry", "sapper":"engineers", "fusilier":"mechanized", "hussar":"light-cavalry", "dragoon":"heavy-cavalry", "spy":"infantry", "guard":"special", "command":"special", "grenadier":"light-artillery", "bombadier":"heavy-artillery"}
airTheater = False
unitTable = {"va1":"infantry", "va2":"infantry", "va3":"infantry", "va5":"infantry", "va6":"infantry", "va7":"infantry", "va9":"infantry", "va12":"infantry", "pa1":"infantry", "pa4":"infantry", "pa6":"infantry", "pa7":"infantry", "pa8":"infantry", "nc1":"infantry", "nc3":"infantry", "md1":"infantry", "md2":"infantry", "nj2":"infantry", "nj4":"infantry", "sap1":"sapper", "sap2":"sapper", "pa1f":"fusilier", "pa2f":"fusilier", "pa3f":"fusilier", "pa4f":"fusilier", "light1":"grenadier", "light2":"grenadier", "nj1f":"fusilier", "nj2f":"fusilier", "nj3f":"fusilier", "mx1":"hussar", "mx2":"hussar", "pl":"dragoon", "mc":"dragoon", "6":"fusilier", "knphyn":"spy", "rebel-guards1":"guard", "rebel-guards2":"guard", "rebel-guards3":"guard", "crnwl":"command", "4":"infantry", "5":"infantry", "10":"infantry", "15":"infantry", "17inf":"infantry", "23":"infantry", "28":"infantry", "33":"infantry", "38":"infantry", "40":"infantry", "44":"infantry", "64":"infantry", "71":"infantry", "72":"infantry", "73":"infantry", "gd1":"sapper", "gd2":"sapper", "lrg":"sapper", "eb":"fusilier", "lg":"fusilier", "dp":"fusilier", "wb":"fusilier", "mg":"fusilier", "ls":"fusilier", "st":"fusilier", "mb":"fusilier", "lt1":"hussar", "lt2":"hussar", "lt3":"hussar", "gr1":"hussar", "gr2":"hussar", "gr3":"hussar", "16":"dragoon", "17":"dragoon", "jag":"dragoon", "6-1":"grenadier", "6-2":"grenadier", "12-1":"bombadier", "12-2":"bombadier", "howe":"spy", "british-guards1":"guard", "british-guards2":"guard", "greene":"command"}
firstTeamTable = {"va1":4, "va2":4, "va3":4, "va5":4, "va6":4, "va7":4, "va9":4, "va12":4, "pa1":4, "pa4":4, "pa6":4, "pa7":4, "pa8":4, "nc1":4, "nc3":4, "md1":4, "md2":4, "nj2":4, "nj4":4, "sap1":4, "sap2":4, "pa1f":6, "pa2f":6, "pa3f":6, "pa4f":6, "light1":8, "light2":8, "nj1f":6, "nj2f":6, "nj3f":6, "mx1":12, "mx2":12, "pl":16, "mc":16, "6":6, "knphyn":10, "rebel-guards1":20, "rebel-guards2":20, "rebel-guards3":20, "crnwl":20}
firstTeamTableOriginal = {"va1":4, "va2":4, "va3":4, "va5":4, "va6":4, "va7":4, "va9":4, "va12":4, "pa1":4, "pa4":4, "pa6":4, "pa7":4, "pa8":4, "nc1":4, "nc3":4, "md1":4, "md2":4, "nj2":4, "nj4":4, "sap1":4, "sap2":4, "pa1f":6, "pa2f":6, "pa3f":6, "pa4f":6, "light1":8, "light2":8, "nj1f":6, "nj2f":6, "nj3f":6, "mx1":12, "mx2":12, "pl":16, "mc":16, "6":6, "knphyn":10, "rebel-guards1":20, "rebel-guards2":20, "rebel-guards3":20, "crnwl":20}
secondTeamTable = {"4":4, "5":4, "10":4, "15":4, "17inf":4, "23":4, "28":4, "33":4, "38":4, "40":4, "44":4, "64":4, "71":4, "72":4, "73":4, "gd1":4, "gd2":4, "lrg":4, "eb":6, "lg":6, "dp":6, "wb":6, "mg":6, "ls":6, "st":6, "mb":6, "lt1":12, "lt2":12, "lt3":12, "gr1":12, "gr2":12, "gr3":12, "16":16, "17":16, "jag":16, "6-1":8, "6-2":8, "12-1":10, "12-2":10, "howe":10, "british-guards1":20, "british-guards2":20, "greene":20}
secondTeamTableOriginal = {"4":4, "5":4, "10":4, "15":4, "17inf":4, "23":4, "28":4, "33":4, "38":4, "40":4, "44":4, "64":4, "71":4, "72":4, "73":4, "gd1":4, "gd2":4, "lrg":4, "eb":6, "lg":6, "dp":6, "wb":6, "mg":6, "ls":6, "st":6, "mb":6, "lt1":12, "lt2":12, "lt3":12, "gr1":12, "gr2":12, "gr3":12, "16":16, "17":16, "jag":16, "6-1":8, "6-2":8, "12-1":10, "12-2":10, "howe":10, "british-guards1":20, "british-guards2":20, "greene":20}
firstHealthTotal = 294
secondHealthTotal = 346
fogOfWar = 6
warheads = 0
draftCapacity = 0
draftStrength = 4
draftType = "infantry"
locationTerrainTable = {"wilson's-lane":"road", "ring's-road":"road", "nottingham-great-road":"road", "wilmington-road":"road", "pyle's-road":"road", "starved-nut-road":"road", "creek-road":"road", "brinton's-ford-road":"road", "ailpin-road":"road", "street-road":"road", "bristol-road":"road", "forks-road":"road", "birmingham-road":"road", "renwick-road":"road", "wylie-road":"road", "wistar's-road":"road", "bullington-road":"road", "westchester-road":"road", "sconnelltown-road":"road", "wilson-forest":"forest", "brinton-forest":"forest", "bennett-forest":"forest", "renwick-forest":"forest", "renwick-north-forest":"forest", "newell-forest":"forest", "bristol-forest":"forest", "the-morass":"forest", "hargen-forest":"forest", "bullington-forest":"forest", "redfield-forest":"forest", "radley-forest":"forest", "rocky-forest":"forest", "hargen-hill":"hill", "newell-hill":"hill", "craig-hill":"hill", "rocky-hill":"hill", "harvey-hill":"hill", "wilson-hill":"hill", "bennett-hill":"hill", "battle-hill":"hill", "brinton-hill":"hill", "roundelay-hill":"hill", "chadd-hill":"hill", "morass-hill":"hill", "birmingham-hill":"hill", "osburn-hill":"hill", "sconnelltown-hill":"hill"}
structureTypeTable = {"wilsontown":"settlement", "bristol":"settlement", "darlington":"settlement", "dilworth":"settlement", "sconnelltown":"settlement", "wilson":"building", "pyle's-mill":"building", "quentin's-tavern":"building", "old-mill":"building", "biggles":"building", "strode's-mill":"building", "underhill":"building", "brinton's-mill":"building", "cheyney":"building", "chadd":"building", "ring":"building", "ailpin":"building", "harvey":"building", "brinton":"building", "bennett":"building", "edgewood":"building", "rockwell":"building", "thornsbury":"building", "redfield":"building", "darlington":"building", "creek-tavern":"building", "birmingham-meeting-house":"building", "swartley":"building", "jones":"building", "davis":"building", "osburns":"building", "fair-meadow":"building", "pyle's-ford":"bridge", "chadd's-ford":"bridge", "brinton's-ford":"bridge", "jones'-ford":"bridge", "wistar's-ford":"bridge", "bullington-ford":"bridge"}
structureHealthTable = {"wilson":2, "pyle's-mill":4, "quentin's-tavern":4, "old-mill":4, "biggles":2, "strode's-mill":4, "underhill":2, "brinton's-mill":4, "cheyney":2, "chadd":2, "ring":2, "ailpin":2, "harvey":2, "brinton":2, "bennett":2, "edgewood":2, "rockwell":2, "thornsbury":2, "redfield":2, "darlington":2, "creek-tavern":4, "birmingham-meeting-house":4, "swartley":2, "jones":2, "davis":2, "osburns":2, "fair-meadow":2, "pyle's-ford":4, "chadd's-ford":4, "brinton's-ford":4, "jones'-ford":4, "wistar's-ford":4, "bullington-ford":4}

# Loadgame function 
def loadGame():
    pass